### PR TITLE
Set env file to jenkins

### PR DESCRIPTION
**Pull request by RasmusUK**
Update the docker compose command for running frontend on jenkins to use the new env file for jenkins.

### CODE REVIEW

**Comment by ravvnen** [comment]
.-"-.           .-"-.           .-"-.           .-"-.           .-"-.
          /  -  \         /  -  \         /  -  \         /  -  \         /  -  \
         /   o   \       /   o   \       /   o   \       /   o   \       /   o   \
        /_________\     /_________\     /_________\     /_________\     /_________\
         |       |       |       |       |       |       |       |       |       |
         |       |       |       |       |       |       |       |       |       |
          \     /         \     /         \     /         \     /         \     /
           `._.'           `._.'           `._.'           `._.'           `._.'

                 ___
               //  ^\         .-"-.          
              // ^ ^ \       /  -  \        
             // ^ ^ ^ \     /   o   \      
            // ^ ^ ^ ^ \   /_________\
            ||^ ^ ^ ^ ^|    |       | 
            || ^ ^ ^ ^ |    |       |
             \\^ ^ ^ ^/      \     / 
              \\^ ^ ^/        `._.'
               `---'

**Comment by RasmusUK** [comment]
@ravvnen Dude du skal ligesom også lige approve den ikke bare kommentere

**Review by ravvnen — APPROVED** [review]
NU HAR JEG REVIEWED

**Comment by RasmusUK** [comment]
Ja tak endelig
Kæmpe blokker

**Pull request merged**
